/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import javax.swing.JOptionPane;

/**
 *
 * @author Krishi
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtsubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtselectuser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(375, 178, 63, 18);

        txtsubmit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtsubmit.setText("SUBMIT");
        txtsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(txtsubmit);
        txtsubmit.setBounds(525, 294, 143, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOG-IN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 80, 102, 30);

        txtselectuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Doctor", "Patient", "Community Admin", "System Admin", " ", " " }));
        getContentPane().add(txtselectuser);
        txtselectuser.setBounds(525, 216, 184, 22);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Role");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(409, 218, 29, 18);
        getContentPane().add(txtusername);
        txtusername.setBounds(525, 136, 184, 22);

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword);
        txtpassword.setBounds(525, 176, 184, 22);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(375, 138, 66, 18);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To sign up as a new user");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(525, 405, 159, 17);

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(525, 440, 154, 38);

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("or");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(595, 371, 11, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Krishi\\Desktop\\Data\\image1.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, -10, 1090, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubmitActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
            String username = txtusername.getText();
            String password = txtpassword.getText();
            String usertype = txtselectuser.getSelectedItem().toString();

            if(username.equals("sysadmin") && password.equals("123") && usertype.equals("System Admin"))
            {
                MainJFrame mainjframe = new MainJFrame();
                mainjframe.show();
            }
          //  else if(username.equals("Rhea") && password.equals("456") && usertype.equals("Patient"))
          //  {
        //        Patientpage patientpage = new Patientpage();
        //        patientpage.show();
           // }
            else if(username.equals("commadmin") && password.equals("789") && usertype.equals("Community Admin"))
            {
                Community comadminpage = new Community();
                comadminpage.show();
            }

            else if(username.equals("doctor1") && password.equals("246") && usertype.equals("Doctor"))
            {
                Doctorpage doctorpage = new Doctorpage();
                doctorpage.show();
            }
            else if(username.equals("") || password.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please enter valid Credentials");
            }
            else{
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
            }
    }//GEN-LAST:event_txtsubmitActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUpJFrame signup = new SignUpJFrame();
        signup.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JComboBox<String> txtselectuser;
    private javax.swing.JButton txtsubmit;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
